### ISSUE TITLE
compilation error with --enable-json

### ISSUE THREAD

**Issue by skoubri** [coova/coova-chilli#376]
Trying to compile on ubuntu 14.04.5LTS geting errors:

checking for res_init in -lresolv... no
checking for json_object_new_object in -ljson-c... no
checking for json_object_new_object in -ljson... no
configure: error: in `/home/useras/coova-chilli-1.4':
configure: error: --enable-json was given, but test for libjson failed
See `config.log' for more details
make: *** [config.status] Error 1
dpkg-buildpackage: error: debian/rules build gave error exit status 2
debuild: fatal error at line 1364:
dpkg-buildpackage -rfakeroot -D -us -uc -i -b failed

This is a clean system trying to install only coovachilli 1.4

Thanks in advance

**Comment by angovil** [comment]
I am also facing similar issue while compiling on debian6. without --enable-json compilation is successful. Please provide the solution that you had applied

**Comment by nzamps** [comment]
On debian8 I added --enable-libjson (after installing libjson via apt-get install libjson-c2)

**Comment by skoubri** [comment]
Hi, yes nzamps is right... libjson-c2 should be installed... But i am facing another problem after compilation... all seems fine, chilli starts but no redirection... DNS query fine, DHCP ok but no login page...
